name: AutoUpdate

on:
  push:
    branches: [main]

jobs:
  compile-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install MPI
        run: |
          sudo apt-get update
          sudo apt-get install -y mpich

      - name: Build
        run: ./build.sh

      - name: Run tests
        run: |
          cd build
          ./test_multiplication

  create-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build Singularity Image
        run: |
          sudo singularity build matrixmulttest.sif container.def

      - name: Run Singularity Container
        run: |
          sudo singularity run matrixmulttest.sif
