name: AutoUpdate

on:
  push:
    branches: [main]

jobs:
  compile-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install MPI
        run: |
          sudo apt-get update
          sudo apt-get install -y mpich

      - name: Build
        run: ./build.sh

      - name: Run tests
        run: |
          cd build
          ./test_multiplication

  create-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Singularity
        run: |
          sudo apt update
          sudo apt install -y \
              build-essential \
              libseccomp-dev \
              pkg-config \
              squashfs-tools \
              cryptsetup \
              curl wget git
          export GOVERSION=1.17.3 OS=linux ARCH=amd64
          wget -O /tmp/go${GOVERSION}.${OS}-${ARCH}.tar.gz \
            https://dl.google.com/go/go${GOVERSION}.${OS}-${ARCH}.tar.gz
          sudo tar -C /usr/local -xzf /tmp/go${GOVERSION}.${OS}-${ARCH}.tar.gz
          echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc
          source ~/.bashrc
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.43.0
          echo 'export PATH=$PATH:$(go env GOPATH)/bin' >> ~/.bashrc
          source ~/.bashrc
          git clone https://github.com/hpcng/singularity.git
          cd singularity
          ./mconfig
          cd ./builddir
          make
          sudo make install 
          export PATH=$PATH:/usr/local/bin
          singularity --version > version.txt

      - name: Build Singularity Image
        run: |
          sudo singularity build matrixmulttest.sif container.def > build.txt 2> builderr.txt

      - name: Run Singularity Container
        run: |
          sudo singularity run matrixmulttest.sif > run.txt 2> runerr.txt

      - name: Show logs
        run: |
          echo "SIngularity version"
          cat version.txt
          echo "Build container"
          cat build.txt
          echo "Build stderr:"
          cat builderr.txt
          echo "Run singularity:"
          cat run.txt
          echo "Run stderr:"
          cat runerr.txt

  gaileo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Connect To Galileo
        run: |
          ssh a08trb45@login.g100.cineca.it


