name: AutoUpdate

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build
        run: ./build.sh

      - name: Run tests
        run: |
          cd build
          ./test_multiplication




