name: AutoUpdate

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install MPI
        run: |
          sudo apt-get update
          sudo apt-get install -y mpich

      - name: Build
        run: ./build.sh

      - name: Run tests
        run: |
          cd build
          ./test_multiplication




